# Generated by Django 3.0.7 on 2024-02-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20240209_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='dimensions',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='height',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='length',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='wheelbase',
            field=models.CharField(default='unkown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='width',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
    ]
