# Generated by Django 3.0.7 on 2024-02-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20240209_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='city',
            field=models.CharField(default='uknown', max_length=100),
            preserve_default=False,
        ),
    ]
