# Generated by Django 3.0.7 on 2024-02-29 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_car_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='Emission_standard',
        ),
        migrations.RemoveField(
            model_name='car',
            name='cO2_emissions',
        ),
        migrations.RemoveField(
            model_name='car',
            name='price',
        ),
    ]
