# Generated by Django 3.0.7 on 2024-02-29 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_auto_20240229_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='interior',
        ),
    ]
