# Generated by Django 3.0.7 on 2024-02-29 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_remove_car_interior'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='minimum_speed',
        ),
    ]
