# Generated by Django 3.0.7 on 2024-03-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_auto_20240304_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine_displacement',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
