# Generated by Django 3.0.7 on 2024-03-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_auto_20240304_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
