# Generated by Django 3.0.7 on 2024-03-04 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_car_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='dimensions',
        ),
    ]
